server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://15.237.135.19:13306/linkpick?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: linkpick
    password: Linkpick@Dev
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      idle-timeout: 60000
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB
      max-request-size: 100MB
  rabbitmq:
    host: 15.237.135.19
    port: 5672
    username: guest
    password: Linkpick@Dev
    exchange:
      signup: signup_topic
    queue:
      cognito: toCognito

logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type: TRACE
      springframework:
        transaction: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

aws:
  cognito:
    accountmanagement:
      clientId: 653rvgbkt5f3eoj83kid9rcf2h
      secretKey: 5oqcmm2ke1g79ebcno8n75db392ec7620l0er63etao1sgju6om
      region: eu-west-3


